#!/bin/sh

# Set these paths appropriately

BIN=/hdd/applications/tree-tagger/bin
CMD=/hdd/applications/tree-tagger/cmd
LIB=/hdd/applications/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
