#!/bin/sh

# Set these paths appropriately

BIN=/hdd/applications/tree-tagger/bin
CMD=/hdd/applications/tree-tagger/cmd
LIB=/hdd/applications/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
