#!/bin/sh

# Set these paths appropriately

BIN=/hdd/applications/tree-tagger/bin
CMD=/hdd/applications/tree-tagger/cmd
LIB=/hdd/applications/tree-tagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/french-abbreviations
PARFILE=${LIB}/french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
